-- AUTOMATICALLY GENERATED by <https://gitlab.com/szest/defripper>

local reg = ...

local L = {}

L.xdecor_chair_node_box = {
	fixed = { { -0.3125, -0.5, 0.1875, -0.1875, 0.5, 0.3125 },
		{ 0.1875,  -0.5,   0.1875,  0.3125,  0.5,    0.3125 },
		{ -0.1875, 0.0625, 0.21875, 0.1875,  0.4375, 0.28125 },
		{ -0.3125, -0.5,   -0.3125, -0.1875, -0.125, -0.1875 },
		{ 0.1875,  -0.5,   -0.3125, 0.3125,  -0.125, -0.1875 },
		{ -0.3125, -0.125, -0.3125, 0.3125,  0,      0.1875 } },
	type = "fixed"
}

L.xdecor_table_node_box = {
	fixed = { { -0.5, 0.375, -0.5, 0.5,   0.5,   0.5 },
		{ -0.15625, -0.5,  -0.15625, 0.15625, 0.375, 0.21875 } },
	type = "fixed"
}

L.arena_lib_sign_node_box = {
	type = "wallmounted",
	wall_bottom = { -0.4445, -0.5, -0.3175, 0.4445, -0.4375, 0.3175 },
	wall_side = { -0.5, -0.3175, -0.4445, -0.4375, 0.3175, 0.4445 },
	wall_top = { -0.4445, 0.5, -0.3175, 0.4445, 0.4375, 0.3175 }
}

minetest.register_node("strategymobs_nodes:barrier", {
	tiles = { { align_style = "world", name = "default_air.png" } },
})

reg({
	_raw_name = "default:stonebrick",
	description = "Stone Brick",
	paramtype2 = "facedir",
	place_param2 = 0,
	tiles = { { align_style = "world", name = "default_stone_brick.png" } },
	type = "node"
})

reg({
	_raw_name = "stairs:slab_stonebrick",
	description = "Stone Brick Slab",
	drawtype = "nodebox",
	light_source = 0,
	node_box = { fixed = { -0.5, -0.5, -0.5, 0.5, 0, 0.5 }, type = "fixed" },
	paramtype = "light",
	paramtype2 = "facedir",
	selection_box = { fixed = { -0.5, -0.5, -0.5, 0.5, 0, 0.5 }, type = "fixed" },
	sunlight_propagates = false,
	tiles = { { backface_culling = true, name = "default_stone_brick.png", align_style = "world" } },
	type = "node"
})

reg({
	_raw_name = "stairs:stair_stonebrick",
	description = "Stone Brick Stair",
	drawtype = "nodebox",
	light_source = 0,
	node_box = {
		fixed = { { -0.5, -0.5, -0.5, 0.5, 0, 0.5 },
			{ -0.5, 0,    0,    0.5, 0.5, 0.5 } },
		type = "fixed"
	},
	paramtype = "light",
	paramtype2 = "facedir",
	selection_box = {
		fixed = { { -0.5, -0.5, -0.5, 0.5, 0, 0.5 },
			{ -0.5, 0,    0,    0.5, 0.5, 0.5 } },
		type = "fixed"
	},
	sunlight_propagates = false,
	tiles = { { backface_culling = true, name = "default_stone_brick.png", align_style = "world" } },
	type = "node"
})

reg({
	_raw_name = "xdecor:chair",
	description = "Chair",
	drawtype = "nodebox",
	node_box = L.xdecor_chair_node_box,
	paramtype = "light",
	paramtype2 = "facedir",
	selection_box = L.xdecor_chair_node_box,
	tiles = { "xdecor_wood.png" },
	type = "node"
})

reg({
	_raw_name = "xdecor:lantern",
	description = "Lantern",
	drawtype = "plantlike",
	inventory_image = "xdecor_lantern_inv.png",
	light_source = 13,
	paramtype = "light",
	selection_box = {
		fixed = { { -0.25, -0.5, -0.25, 0.25, 0.5, 0.25 } },
		type = "fixed"
	},
	sunlight_propagates = true,
	tiles = { {
		animation = { length = 1.5, type = "vertical_frames" },
		name = "xdecor_lantern.png"
	} },
	type = "node",
	walkable = false,
	wield_image = "xdecor_lantern_inv.png"
})

reg({
	_raw_name = "xdecor:table",
	description = "Table",
	drawtype = "nodebox",
	node_box = L.xdecor_table_node_box,
	paramtype = "light",
	paramtype2 = "facedir",
	selection_box = L.xdecor_table_node_box,
	tiles = { "xdecor_wood.png" },
	type = "node"
})